2025-07-07 15:34:38,001 p=4425 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:34:38,001 p=4425 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:34:38,189 p=4425 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:34:38,189 p=4425 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

2025-07-07 15:41:52,628 p=4536 u=root n=ansible WARNING| [WARNING]: No python interpreters found for host 192.168.56.131 (tried ['python3.13', 'python3.12', 'python3.11', 'python3.10',
'python3.9', 'python3.8', '/usr/bin/python3', 'python3'])

2025-07-07 15:41:52,628 p=4536 u=root n=ansible INFO| 192.168.56.131 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.56.131 closed.\r\n",
    "module_stdout": "/bin/sh: /usr/bin/python3: No such file or directory\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
2025-07-07 15:41:52,860 p=4536 u=root n=ansible WARNING| [WARNING]: Platform linux on host 192.168.56.142 is using the discovered Python interpreter at /usr/bin/python3, but future
installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
core/2.18/reference_appendices/interpreter_discovery.html for more information.

2025-07-07 15:41:52,860 p=4536 u=root n=ansible INFO| 192.168.56.142 | CHANGED | rc=0 >>
ok

